
PASSENGER_EMAIL = 'passenger@gmail.com'
PASSENGER_PASSWORD = 'Password123'

DRIVER_EMAIL = 'driver@gmail.com'
DRIVER_PASSWORD = 'Password123'

ADMIN_EMAIL = 'admin@gmail.com'
ADMIN_PASSWORD = 'Password123'

ACCOUNT_ACTIVATION_ID = '123456'
ACCOUNT_ACTIVATION_ID_EXPIRED = '654321'
ACCOUNT_ACTIVATION_ID_NON_EXISTING = '123321'
